export enum Campus {
    UW = 'UW',
    CGC = 'CGC',
    REN = 'REN',
    STJ = 'STJ',
    UTD = 'UTD',
    WLU = 'WLU',
    BLND = 'BLND',
    BLNDG = 'BLNDG',
    BLNDJ = 'BLNDJ',
    BLNDR = 'BLNDR',
    BLNDT = 'BLNDT',
    ONLN = 'ONLN',
    ONLNG = 'ONLNG',
    ONLNJ = 'ONLNJ',
    ONLNR = 'ONLNR',
    ONLNT = 'ONLNT',
    OFF = 'OFF',
}
